name: Octo Organization CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: python my_script.py
